### ISSUE TITLE
When opening Build Folder, the file is a generic un-openable file

### ISSUE THREAD

**Issue by Natron4** [jackcrane/apple-music-presence#10]
![image](https://user-images.githubusercontent.com/114454838/192411765-85f32b19-3bde-4f9f-8567-62d7b94c5a21.png)

**Comment by edalzell** [comment]
You're on Windows, this is for macOS

**Comment by jackcrane** [comment]
As @edalzell mentioned, this is a mac-os only project. Unfortunately it is based on Applescript which is mac only.
