### ISSUE TITLE
no album art

### ISSUE THREAD

**Issue by noyourthesucker** [jackcrane/apple-music-presence#11]
broken image shown instead of display art :(

**Comment by yourlocaldumbfoundedgay** [comment]
same over here on MBP 14", works perfectly fine otherwise though
did notice it would say new song in the terminal prompt; perhaps that's related?

**Comment by Bryceayo** [comment]
Im getting this too, idk ill just ask chatgpt to fix it or somn

**Comment by jackcrane** [comment]
Many users have noticed an issue with the display of images. I will investigate, but no promises :)

**Comment by leevi-laitala** [comment]
Any updates on this?

**Comment by asheswook** [comment]
I investigated this project, and I found it works with @jackcrane's private object storage. The object storage server seems to closed (DigitalOcean Storage, Access denied). It is uploaded to @jackcrane's storage whenever a new album cover is found, and I tried to access the already uploaded album cover in README on this repo, but it is still denied access. This suggests that there is no problem with the upload function. I think it's just because his storage is closed.

**Comment by anthonyhuang07** [comment]
![image](https://user-images.githubusercontent.com/90001131/220488384-412d4c1a-fd68-42ee-a745-496cebcd4a23.png)

still broken for me aswell

**Comment by VariantT505** [comment]
Same here, still no album art.

**Comment by jackcrane** [comment]
# Project has reached EOL. Bugs will not be fixed. If you donated on BMAC, reach out and I will process a refund for you.

**Comment by fau1095** [comment]
> Project has reached EOL. Bugs will not be fixed. If you donated on BMAC, reach out and I will process a refund for you.

any reason for it? it was a cool project

**Comment by jackcrane** [comment]
Thanks! I have started college as a full time student, am working in a research lab, and still have a part-time software development job. Unfortunately I am at a point where the RoI of writing code is a really important factor. Fighting burnout, each line of code needs to be extremely worthwhile either for pay or for school, and this project satisfies neither. Additionally, discord has made some changes to how they handle these images. This is not a complete no-op but it would take several hours of hard work to update.

Thanks to you all and to anyone reading this for your interest.
