### ISSUE TITLE
Apple silicon?

### ISSUE THREAD

**Issue by PriZmRL** [jackcrane/apple-music-presence#3]
It works great on intel binary, will it be possible to build this for apple silicon?

**Comment by jackcrane** [comment]
We use vercel/pkg under the hood, and there _is_ build support but it is immediately killed by the kernel. More info https://github.com/vercel/pkg/issues/1023

**Comment by MaybeThisIsRu** [comment]
The app runs, connects to Discord, detects songs, but the status doesn't actually update on Discord. Is that related to this? I'm on M1 as well.

**Comment by jackcrane** [comment]
That may be on our side or on Discord's side. I will investigate

**Comment by jackcrane** [comment]
# Project has reached EOL. Bugs will not be fixed. If you donated on BMAC, reach out and I will process a refund for you.
