### ISSUE TITLE
Paid version?

### ISSUE THREAD

**Issue by nothingspecialguild** [jackcrane/apple-music-presence#4]
Is there scope to have a paid version that doesn't pop your website up upon launch?

**Comment by jackcrane** [comment]
yep! https://www.buymeacoffee.com/jackcrane/my-urgent-contact-information-information. Thanks for the support and let me know if you want any features

**Comment by nothingspecialguild** [comment]
Cheers!

**Comment by jackcrane** [comment]
ofc! Thanks for the support!
