### ISSUE TITLE
Is it for mac-os only?

### ISSUE THREAD

**Issue by Eithann5** [jackcrane/apple-music-presence#7]
using win-10.
For some reason my pc doesn't recognize the file correctly. 
![image](https://user-images.githubusercontent.com/47326438/169695467-d3e06d9a-34c8-4ad2-b504-ecea68e72827.png)
![image](https://user-images.githubusercontent.com/47326438/169695475-eae136e2-7250-423e-9378-8b766747b185.png)

What am i doing wrong here?
Thanks in advance!

**Comment by jackcrane** [comment]
Unfortunately amp uses AppleScript as its core functionality and AS is only available on MacOS, so AMP is only available for macs. sorry!
