### ISSUE TITLE
Annoying link popup

### ISSUE THREAD

**Issue by developerfromjokela** [jackcrane/apple-music-presence#8]
I understand that you want donations, but this is getting very annoying.
Could you please remove that link opening  command?

**Comment by jackcrane** [comment]
Unfortunately, Apple Music presence cost me quite a bit to run per month, and donations are the only way I can afford to keep it going, and they still don't cover the full cost most months. I understand this is not the answer you are hoping for, but i do sell a version that does not have the pop-up [here](https://www.buymeacoffee.com/jackcrane/e/66210)
